### ISSUE TITLE
Error with v11.9 (Blackfire62's fork)

### ISSUE THREAD

**Issue by Augustin37** [Th3Tr0LLeR/SkinsRestorer---Maro#105]
Hello, I have an error when I load your latest version of SkinsRestorer:
```java
[02:30:06] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v11.9 (Blackfire62's fork)
[02:30:06] [Server thread/ERROR]: Error occurred while enabling SkinsRestorer v11.9 (Blackfire62's fork) (Is it up to date?)
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542) ~[?:1.8.0_91]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_91]
	at skinsrestorer.shared.utils.YamlConfig.getInt(YamlConfig.java:68) ~[?:?]
	at skinsrestorer.shared.storage.ConfigStorage.init(ConfigStorage.java:49) ~[?:?]
	at skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.9.4.jar:git-Paper-772]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.9.4.jar:git-Paper-772]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.4.jar:git-Paper-772]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.9.4.jar:git-Paper-772]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.9.4.jar:git-Paper-772]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:205) [patched_1.9.4.jar:git-Paper-772]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:573) [patched_1.9.4.jar:git-Paper-772]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[02:30:06] [Server thread/INFO]: [SkinsRestorer] Disabling SkinsRestorer v11.9 (Blackfire62's fork)
```

**Comment by Blackfire62** [comment]
You did not read my post and did not delete your current config.yml and messages.yml so the plugin can replace them with new ones.

**Comment by Augustin37** [comment]
Actually I did a clean server without any config to test it. Anyway, it seems like you fix the problem in v11.9.1

Thank you

**Comment by Blackfire62** [comment]
Actually I was wrong and there was an  error which didnt allow the config to load on first reset. Second reset would work.

**Comment by Augustin37** [comment]
Thank you :)
