### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by mcbleazz** [Th3Tr0LLeR/SkinsRestorer---Maro#117]
03:35:56] [User Authenticator #10/INFO]: UUID of player Swiffty is 2f7033c8-a087-3efc-860c-c4c270c34062
[03:35:56] [Netty Epoll Server IO #0/WARN]: java.lang.reflect.InvocationTargetException
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:96)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at skinsrestorer.shared.utils.YamlConfig.save(YamlConfig.java:119)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at skinsrestorer.shared.utils.YamlConfig.set(YamlConfig.java:47)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.removePlayerSkin(SkinStorage.java:47)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:185)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:207)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at skinsrestorer.bukkit.listeners.SkinsPacketHandler.write(SkinsPacketHandler.java:75)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_10_R1.NetworkManager$4.run(NetworkManager.java:200)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[03:35:56] [Netty Epoll Server IO #0/WARN]: Caused by: java.lang.NullPointerException
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:400)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.access$1600(Emitter.java:62)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingSimpleValue.expect(Emitter.java:641)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:216)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:181)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:205)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:112)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68)
[03:35:56] [Netty Epoll Server IO #0/WARN]: 	... 23 more
[03:35:56] [Netty Epoll Server IO #3/WARN]: java.lang.reflect.InvocationTargetException
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:96)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at skinsrestorer.shared.utils.YamlConfig.save(YamlConfig.java:119)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at skinsrestorer.shared.utils.YamlConfig.set(YamlConfig.java:47)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.removePlayerSkin(SkinStorage.java:49)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:185)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:207)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at skinsrestorer.bukkit.listeners.SkinsPacketHandler.write(SkinsPacketHandler.java:75)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_10_R1.NetworkManager$4.run(NetworkManager.java:200)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[03:35:56] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.NullPointerException
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:400)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.access$1600(Emitter.java:62)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingSimpleValue.expect(Emitter.java:641)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:216)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:181)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:205)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:112)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68)
[03:35:56] [Netty Epoll Server IO #3/WARN]: 	... 23 more
[03:35:56] [Netty Epoll Server IO #1/WARN]: java.lang.reflect.InvocationTargetException
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:96)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at skinsrestorer.shared.utils.YamlConfig.save(YamlConfig.java:119)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at skinsrestorer.shared.utils.YamlConfig.set(YamlConfig.java:47)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.removePlayerSkin(SkinStorage.java:49)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:185)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:207)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at skinsrestorer.bukkit.listeners.SkinsPacketHandler.write(SkinsPacketHandler.java:75)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_10_R1.NetworkManager$4.run(NetworkManager.java:200)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[03:35:56] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.NullPointerException
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:400)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.access$1600(Emitter.java:62)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingSimpleValue.expect(Emitter.java:641)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:216)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:181)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:205)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:112)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68)
[03:35:56] [Netty Epoll Server IO #1/WARN]: 	... 23 more

**Comment by Mario359** [comment]
I have this error too
And skins does not work
