### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by RikoDEV** [Th3Tr0LLeR/SkinsRestorer---Maro#136]
Hi, I get error on player join on bungeecord console: [latest plugin version]

```
19:58:14 [INFO] Enabling AdvancedBan on Version 2.0.0
19:58:14 [INFO] Coded by Leoko | Web: dev.skamps.eu
19:58:14 [INFO] Enabled plugin AdvancedBan version 2.0.0 by Leoko
19:58:14 [SEVERE] Jul 31, 2016 7:58:14 PM com.zaxxer.hikari.HikariDataSource <init>
INFO: HikariPool-1 - Started.

19:58:14 [INFO] Enabled plugin FastLogin version 1.7 by games647, http://github.com/games647/FastLogin/graphs/contributors
19:58:14 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:5973754:unknown by SpigotMC
19:58:14 [INFO] [ServerListPlus] [Core] Reloading configuration...
19:58:14 [INFO] [ServerListPlus] [Core] Loaded configuration: ServerStatusConf
19:58:14 [INFO] [ServerListPlus] [Core] Loaded configuration: PluginConf
19:58:14 [INFO] [ServerListPlus] [Core] Reloading saved player identities...
19:58:14 [INFO] [ServerListPlus] Successfully loaded!
19:58:14 [INFO] Enabled plugin ServerListPlus version 3.4.7-SNAPSHOT by Minecrell <https://github.com/Minecrell>
19:58:14 [INFO] Enabled plugin Yamler version 2.4.0-SNAPSHOTb-16 by geNAZt
19:58:14 [INFO] Enabled plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:5973754:unknown by SpigotMC
19:58:14 [SEVERE] Jul 31, 2016 7:58:14 PM io.netty.channel.DefaultChannelId defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: f8:82:85:f9:56:62:87:45

19:58:14 [INFO] Listening on /0.0.0.0:25565
19:58:14 [INFO] Started query on /0.0.0.0:25565
19:58:29 [INFO] [/**.**.**.**:**29] <-> InitialHandler has connected
19:58:31 [SEVERE] java.lang.ClassNotFoundException: org.bukkit.configuration.file.YamlConfiguration
19:58:31 [SEVERE] at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
19:58:31 [SEVERE] at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
19:58:31 [SEVERE] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
19:58:31 [SEVERE] at java.lang.Class.forName0(Native Method)
19:58:31 [SEVERE] at java.lang.Class.forName(Class.java:264)
19:58:31 [SEVERE] at skinsrestorer.shared.utils.YamlConfig.reload(YamlConfig.java:146)
19:58:31 [SEVERE] at skinsrestorer.shared.storage.SkinStorage.removePlayerSkin(SkinStorage.java:48)
19:58:31 [SEVERE] at skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:191)
19:58:31 [SEVERE] at skinsrestorer.bungee.listeners.LoginListener.onLogin(LoginListener.java:23)
19:58:31 [SEVERE] at net.techcable.event4j.asm.GeneratedEventExecutor1.fire(Unknown Source)
19:58:31 [SEVERE] at net.techcable.event4j.RegisteredListener.fire(RegisteredListener.java:39)
19:58:31 [SEVERE] at net.techcable.event4j.HandlerList.fire(HandlerList.java:16)
19:58:31 [SEVERE] at net.techcable.event4j.EventBus.fire(EventBus.java:35)
19:58:31 [SEVERE] at net.md_5.bungee.event.EventBus.post(EventBus.java:25)
19:58:31 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:376)
19:58:31 [SEVERE] at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:529)
19:58:31 [SEVERE] at net.md_5.bungee.connection.InitialHandler.access$600(InitialHandler.java:63)
19:58:31 [SEVERE] at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:422)
19:58:31 [SEVERE] at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:411)
19:58:31 [SEVERE] at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:68)
19:58:31 [SEVERE] at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:59)
19:58:31 [SEVERE] at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14)
19:58:31 [SEVERE] at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
19:58:31 [SEVERE] at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
19:58:31 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
19:58:31 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
19:58:31 [SEVERE] at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
19:58:31 [SEVERE] at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1066)
19:58:31 [SEVERE] at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
19:58:31 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
19:58:31 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
19:58:31 [SEVERE] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
19:58:31 [SEVERE] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
19:58:31 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
19:58:31 [SEVERE] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
19:58:31 [SEVERE] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:961)
19:58:31 [SEVERE] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
19:58:31 [SEVERE] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
19:58:31 [SEVERE] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
19:58:31 [SEVERE] at java.lang.Thread.run(Thread.java:745)
19:58:32 [SEVERE] java.lang.ClassNotFoundException: org.bukkit.configuration.file.YamlConfiguration
19:58:32 [SEVERE] at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
19:58:32 [SEVERE] at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
19:58:32 [SEVERE] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
19:58:32 [SEVERE] at java.lang.Class.forName0(Native Method)
19:58:32 [SEVERE] at java.lang.Class.forName(Class.java:264)
19:58:32 [SEVERE] at skinsrestorer.shared.utils.YamlConfig.reload(YamlConfig.java:146)
19:58:32 [SEVERE] at skinsrestorer.shared.storage.SkinStorage.removePlayerSkin(SkinStorage.java:48)
19:58:32 [SEVERE] at skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:191)
19:58:32 [SEVERE] at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:213)
19:58:32 [SEVERE] at skinsrestorer.bungee.SkinApplier$1.run(SkinApplier.java:23)
19:58:32 [SEVERE] at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
19:58:32 [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:58:32 [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:58:32 [SEVERE] at java.lang.Thread.run(Thread.java:745)
19:58:32 [INFO] [PolskiRiko2|/********:2***] <-> ServerConnector [lobby] has connected
>
```

**Comment by EMC3** [comment]
better indented stacktraces and more significative title: https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/137
