### ISSUE TITLE
Doesn't work in PaperSpigot 1.7.10

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Th3Tr0LLeR/SkinsRestorer---Maro#169]
SkinsRestorer doesn't work in 1.7.10, the plugin is enabled successfully and the commands work, but your skin doesn't change (I'm using Minecraft 1.8.9 to connect to the server)

**Comment by Th3Tr0LLeR** [comment]
Detailed info would be a good start of an report.

**Comment by MrPowerGamerBR** [comment]
@Th3Tr0LLeR what info do you need?

**Comment by Th3Tr0LLeR** [comment]
Server version, Plugins list, SkinsRestorer version, etc.. Maybe log file

**Comment by MrPowerGamerBR** [comment]
@Th3Tr0LLeR  *facepalm*

Now that I seen ProtocolLib didn't start correctly due to missing classes (I use a custom PaperSpigot 1.7.10 fork and I updated Guava, that's why it failed to start), well, I think this can be closed, right?

**Comment by Th3Tr0LLeR** [comment]
Yeah. Make sure to check things before reporting again. Thanks :)

Best Regards,
~SkinsRestorer Team

**Comment by MrPowerGamerBR** [comment]
@Th3Tr0LLeR oh wait, ProtocolLib is actually working, so...

Version:
```
[15:24:19 INFO]: This server is running DreamSpigotPlus version git-DreamSpigotPlus-549b970 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
```

Yeah, I use a custom PaperSpigot 1.7.10 fork (It has updated Guava so I can use ViaVersion in 1.7.10), but IIRC it also happens in PaperSpigot 1.7.10, I test this ASAP.

Plugins:
```
[15:24:58 INFO]: Plugins (19): SkinsRestorer, WorldEdit, EmptyWorldGenerator, mcMMO, ViaVersion, Vault, Multiverse-Core, ProtocolLib, WorldGuard, SimpleClans, Legendchat, ChestShop, Essentials, CompatNoCheatPlus, HolographicDisplays, MineResetLite, EssentialsSpawn, HolographicDisplaysPatch, NoCheatPlus
```

Server log:
https://gist.github.com/MrPowerGamerBR/19e396b9e85b2963bdeb2f5a5a9f57bd

This was also happening to me waaaay back when my main server was still running 1.7.10 (now it runs 1.8.8 and SkinsRestorer works fine with it) but I never submitted a issue back then.

**Comment by MrPowerGamerBR** [comment]
@Th3Tr0LLeR also something I found out:

SkinsRestorer *does* work if I use HexagonMC (a 1.7 to 1.10 BungeeCord) and if I use SkinsRestorer in HexagonMC instead of the Spigot server.

**Comment by Blackfire62** [comment]
So what is the problem?

**Comment by MrPowerGamerBR** [comment]
@Blackfire62 if I add SkinsRestorer in a vanilla PaperSpigot 1.7.10, the skins doesn't work at all, all 1.8.X clients can't see their own skin or any other player's skins.

So, yeah, that's the issue, if I use SkinsRestorer on a BungeeCord (ON A BUNGEECORD NOT ON THE PAPERSPIGOT SERVER) it works.

**Comment by MrPowerGamerBR** [comment]
@Blackfire62 @Th3Tr0LLeR ha! Now I found out that it throws a stacktrace when a player joins!

Here is the stacktrace:
```
06:42:11 ERROR]: Could not pass event PlayerJoinEvent to SkinsRestorer v12.9.1-BETA
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:301) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:186) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:221) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [paperspigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [paperspigot.jar:git-DreamSpigotPlus-549b970]
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/ChannelDuplexHandler
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_102]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_102]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_102]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_102]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
        at skinsrestorer.bukkit.SkinsRestorer$2.onJoin(SkinsRestorer.java:136) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelDuplexHandler
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_102]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_102]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_102]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_102]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
        at skinsrestorer.bukkit.SkinsRestorer$2.onJoin(SkinsRestorer.java:136) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[paperspigot.jar:git-DreamSpigotPlus-549b970]
        ... 14 more
```
Maybe SkinsRestorer is using the wrong Netty package, because in 1.7.10 (up until 1.8.3 IIRC) the Netty package is in "net.minecraft.util.io.netty", not in "io.netty"

**Comment by MrPowerGamerBR** [comment]
I think someone forgot to check the NMS version here 😉 

```
			Bukkit.getPluginManager().registerEvents(new Listener() {

				@EventHandler(priority = EventPriority.LOWEST)
				public void onJoin(PlayerJoinEvent e) {
					PacketListener.inject(e.getPlayer());

				}

			}, this);
```
It will always going to inject the 1.8 PacketListener, not the 1.7 PacketListener.

**Comment by Th3Tr0LLeR** [comment]
Ooh, Lol. That's @Blackfire62's fault :D

**Comment by xknat** [comment]
also redone in v13.1.1
