### ISSUE TITLE
Doesn't work on BungeeCord 1.12 (HexagonMC)

### ISSUE THREAD

**Issue by DanielAlves123** [Th3Tr0LLeR/SkinsRestorer---Maro#203]
Hi, it doesn't work with latest HexagonMC bungeecord. I'm just using SkinsRestorer on bungee. Also when typing 'sr props PLAYER' it shows this error:
`[INFO] An internal error occurred whilst executing this command, please check the console log for details.
[WARNING] Error in dispatching command
java.lang.NullPointerException
    at skinsrestorer.bungee.commands.AdminCommands.execute(AdminCommands.java:222)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:113)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
`
I just want to use default skins option.
Settings skins with the command works.

**Comment by xknat** [comment]
The command sr props does not work. Downgrade to the version i mentioned inside #announcements in discord

**Comment by DanielAlves123** [comment]
Cool, but THE SKINS DON'T WORK.

**Comment by xknat** [comment]
@DanielAlves123 what i am seeing here is the ussage of a admin command.
give me the error logg or join discord for "support" cuz its not a bug
