### ISSUE TITLE
Plugin not loading in 1.12 Bukkit

### ISSUE THREAD

**Issue by CraftMechanics** [Th3Tr0LLeR/SkinsRestorer---Maro#204]
SkinRestorer will not load on a 1.12 bukkit server

```
[13:59:44] [Server thread/INFO]: Starting minecraft server version 1.12
[13:59:44] [Server thread/INFO]: Loading properties
[13:59:44] [Server thread/INFO]: Default game type: SURVIVAL
[13:59:44] [Server thread/INFO]: Generating keypair
[13:59:44] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:59:44] [Server thread/INFO]: Using default channel type
[13:59:44] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-d603539 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[13:59:45] [Server thread/INFO]: [SkinsRestorer] Loading SkinsRestorer v13.1.2
[13:59:45] [Server thread/INFO]: Preparing level "world"
[13:59:45] [Server thread/INFO]: Preparing start region for level 0 (Seed: 2478902686230809419)
[13:59:46] [Server thread/INFO]: Preparing spawn area: 39%
[13:59:47] [Server thread/INFO]: Preparing start region for level 1 (Seed: 2478902686230809419)
[13:59:47] [Server thread/INFO]: Preparing start region for level 2 (Seed: 2478902686230809419)
[13:59:48] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v13.1.2
[13:59:48] [Server thread/ERROR]: Error occurred while enabling SkinsRestorer v13.1.2 (Is it up to date?)
java.lang.NullPointerException: null
	at skinsrestorer.bukkit.SkinsRestorer.log(SkinsRestorer.java:57) ~[?:?]
	at skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:115) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.jar:git-Bukkit-d603539]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:401) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.12.jar:git-Bukkit-d603539]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[13:59:48] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:59:48] [Server thread/INFO]: Done (3.044s)! For help, type "help" or "?"
```

**Comment by xknat** [comment]
We know.
Join discord so you know all 7 bugs in this version

**Comment by xknat** [comment]
has been solved
