### ISSUE TITLE
TimeOut?

### ISSUE THREAD

**Issue by Ant4rez** [Th3Tr0LLeR/SkinsRestorer---Maro#221]
### What doesn't work (or what feature do you request)?

Skins doesn't appears.

```
11:07:53 [INFO] [SkinsRestorer] Switching to proxy to get skin property.
11:07:53 [INFO] [SkinsRestorer] Proxy list is empty. Getting one.
11:07:58 [SEVERE] java.net.SocketTimeoutException: Read timed out
11:07:58 [SEVERE]   at java.net.SocketInputStream.socketRead0(Native Method)
11:07:58 [SEVERE]   at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
11:07:58 [SEVERE]   at java.net.SocketInputStream.read(SocketInputStream.java:171)
11:07:58 [SEVERE]   at java.net.SocketInputStream.read(SocketInputStream.java:141)
11:07:58 [SEVERE]   at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
11:07:58 [SEVERE]   at sun.security.ssl.InputRecord.read(InputRecord.java:503)
11:07:58 [SEVERE]   at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
11:07:58 [SEVERE]   at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
11:07:58 [SEVERE]   at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
11:07:58 [SEVERE]   at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
11:07:58 [SEVERE]   at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
11:07:58 [SEVERE]   at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
11:07:58 [SEVERE]   at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
11:07:58 [SEVERE]   at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
11:07:58 [SEVERE]   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
11:07:58 [SEVERE]   at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
11:07:58 [SEVERE]   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
11:07:58 [SEVERE]   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
11:07:58 [SEVERE]   at java.security.AccessController.doPrivileged(Native Method)
11:07:58 [SEVERE]   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
11:07:58 [SEVERE]   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
11:07:58 [SEVERE]   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
11:07:58 [SEVERE]   at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:52)
11:07:58 [SEVERE]   at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:34)
11:07:58 [SEVERE]   at skinsrestorer.shared.utils.ProxyManager.getList(ProxyManager.java:25)
11:07:58 [SEVERE]   at skinsrestorer.shared.utils.MojangAPI.readURLProxy(MojangAPI.java:167)
11:07:58 [SEVERE]   at skinsrestorer.shared.utils.MojangAPI.getUUIDProxy(MojangAPI.java:118)
11:07:58 [SEVERE]   at skinsrestorer.shared.utils.MojangAPI.getUUID(MojangAPI.java:111)
11:07:58 [SEVERE]   at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:108)
11:07:58 [SEVERE]   at skinsrestorer.bungee.SkinApplier$1.run(SkinApplier.java:25)
11:07:58 [SEVERE]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11:07:58 [SEVERE]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:07:58 [SEVERE]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:07:58 [SEVERE]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:07:58 [SEVERE]   at java.lang.Thread.run(Thread.java:748)
```

### What version of SkinsRestorer do you use?

SkinRestorer 13.2 https://www.spigotmc.org/resources/skinsrestorer.2124/update?update=203332

**Comment by DoNotSpamPls** [comment]
The problem is caused by getmeproxy.com being down from time to time. For now it seems to be stable, but we'll see

**Comment by xknat** [comment]
for support, join our discord support server! [https://discord.me/skinsrestorer](https://discord.me/skinsrestorer)
