### ISSUE TITLE
SkinsRestorer doesn't work for SpongeForge

### ISSUE THREAD

**Issue by Josegamesall** [Th3Tr0LLeR/SkinsRestorer---Maro#232]
Any comand works in SpongeForge
Minecraft version: 1.10.2
I used the new release 13.3 and not work.
How can I fix that?

**Comment by Josegamesall** [comment]
THIS IS THE LOG:



[18:50:10] [Server thread/DEBUG] [FML/]:  	Valid Signatures:
[18:50:10] [Server thread/DEBUG] [FML/]: 		(e3c3d50c7c986df74c645c0ac54639741c90a557) FML	(Forge Mod Loader	8.0.99.99)	forge.jar
[18:50:10] [Server thread/DEBUG] [FML/]: 		(e3c3d50c7c986df74c645c0ac54639741c90a557) Forge	(Minecraft Forge	12.18.3.2477)	forge.jar
[18:50:10] [Server thread/DEBUG] [FML/]:  	Missing Signatures:
[18:50:10] [Server thread/DEBUG] [FML/]: 		mcp	(Minecraft Coder Pack	9.19)	minecraft.jar
[18:50:10] [Server thread/DEBUG] [FML/]: 		spongeapi	(SpongeAPI	5.2.0-SNAPSHOT-c675e80)	minecraft.jar
[18:50:10] [Server thread/DEBUG] [FML/]: 		sponge	(SpongeForge	1.10.2-2477-5.2.0-BETA-2793)	spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar
[18:50:10] [Server thread/DEBUG] [FML/]: 		changeskin	(ChangeSkin	3.0)	ChangeSkin.jar
[18:50:10] [Server thread/DEBUG] [FML/]: 		flexiblelogin	(FlexibleLogin	0.16.8)	flexiblelogin-0.16.8.jar
[18:50:10] [Server thread/DEBUG] [FML/]: 		mercurius_updater	(mercurius_updater	1.0)	MercuriusUpdater-1.10.2.jar
[18:50:10] [Server thread/DEBUG] [FML/]: 		nucleus	(Nucleus	1.1.10-LTS-COMMUNITY-S5.1)	Nucleus-1.1.10-LTS-COMMUNITY-S5.1-MC1.10.2-plugin.jar
[18:50:10] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue
[18:50:10] [Server thread/ERROR] [FML/]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	UC	Forge{12.18.3.2477} [Minecraft Forge] (forge.jar) 
	UC	spongeapi{5.2.0-SNAPSHOT-c675e80} [SpongeAPI] (minecraft.jar) 
	UC	sponge{1.10.2-2477-5.2.0-BETA-2793} [SpongeForge] (spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar) 
	UE	changeskin{3.0} [ChangeSkin] (ChangeSkin.jar) 
	UC	flexiblelogin{0.16.8} [FlexibleLogin] (flexiblelogin-0.16.8.jar) 
	UC	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UC	nucleus{1.1.10-LTS-COMMUNITY-S5.1} [Nucleus] (Nucleus-1.1.10-LTS-COMMUNITY-S5.1-MC1.10.2-plugin.jar) 
[18:50:10] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[18:50:10] [Server thread/ERROR] [FML/]: Caught exception from ChangeSkin (changeskin)
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for changeskin.slf4j.Logger was bound.
  while locating changeskin.slf4j.Logger
    for parameter 0 at com.github.games647.changeskin.sponge.ChangeSkinSponge.<init>(ChangeSkinSponge.java:49)
  at org.spongepowered.common.guice.SpongePluginGuiceModule.configure(SpongePluginGuiceModule.java:68)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar:1.10.2-2477-5.2.0-BETA-2793]
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar:1.10.2-2477-5.2.0-BETA-2793]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar:1.10.2-2477-5.2.0-BETA-2793]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:226) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar:1.10.2-2477-5.2.0-BETA-2793]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:233) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar:1.10.2-2477-5.2.0-BETA-2793]
	at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:286) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar:1.10.2-2477-5.2.0-BETA-2793]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:561) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[18:50:10] [Server thread/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:299]: Negative index in crash report handler (0/5)
[18:50:10] [Server thread/WARN] [FML/]: Can't revert to frozen GameData state without freezing first.
[18:50:10] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStoppedEvent to mod mcp
[18:50:10] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStoppedEvent to mod mcp
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Minecraft Coder Pack took 0,000s
[18:50:10] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStoppedEvent to mod FML
[18:50:10] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStoppedEvent to mod FML
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Forge Mod Loader took 0,000s
[18:50:10] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStoppedEvent to mod Forge
[18:50:10] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStoppedEvent to mod Forge
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Minecraft Forge took 0,001s
[18:50:10] [Server thread/TRACE] [spongeapi/spongeapi]: Sending event FMLServerStoppedEvent to mod spongeapi
[18:50:10] [Server thread/TRACE] [spongeapi/spongeapi]: Sent event FMLServerStoppedEvent to mod spongeapi
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - SpongeAPI took 0,000s
[18:50:10] [Server thread/TRACE] [sponge/sponge]: Sending event FMLServerStoppedEvent to mod sponge
[18:50:10] [Server thread/TRACE] [sponge/sponge]: Sent event FMLServerStoppedEvent to mod sponge
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - SpongeForge took 0,009s
[18:50:10] [Server thread/TRACE] [changeskin/changeskin]: Sending event FMLServerStoppedEvent to mod changeskin
[18:50:10] [Server thread/TRACE] [changeskin/changeskin]: Sent event FMLServerStoppedEvent to mod changeskin
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - ChangeSkin took 0,000s
[18:50:10] [Server thread/TRACE] [flexiblelogin/flexiblelogin]: Sending event FMLServerStoppedEvent to mod flexiblelogin
[18:50:10] [Server thread/TRACE] [flexiblelogin/flexiblelogin]: Sent event FMLServerStoppedEvent to mod flexiblelogin
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - FlexibleLogin took 0,000s
[18:50:10] [Server thread/TRACE] [mercurius_updater/mercurius_updater]: Sending event FMLServerStoppedEvent to mod mercurius_updater
[18:50:10] [Server thread/TRACE] [mercurius_updater/mercurius_updater]: Sent event FMLServerStoppedEvent to mod mercurius_updater
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - mercurius_updater took 0,000s
[18:50:10] [Server thread/TRACE] [nucleus/nucleus]: Sending event FMLServerStoppedEvent to mod nucleus
[18:50:10] [Server thread/TRACE] [nucleus/nucleus]: Sent event FMLServerStoppedEvent to mod nucleus
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Nucleus took 0,000s
[18:50:10] [Server thread/DEBUG] [FML/]: Bar Finished: ServerStopped took 0,012s
[18:50:10] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[18:50:10] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[18:50:10] [Server thread/DEBUG] [mixin/]: Mixing api.event.MixinAbstractEvent from mixins.forge.core.json into org.spongepowered.api.event.impl.AbstractEvent

**Comment by DoNotSpamPls** [comment]
SkinsRestorer doesn't support Sponge.

**Comment by Josegamesall** [comment]
And how can I put skins?

**Comment by DoNotSpamPls** [comment]
We added Sponge support recently, it will be available in the next release (no ETA on that)
