### ISSUE TITLE
Massive Error Spam (getmeproxy.com is down)

### ISSUE THREAD

**Issue by theJ3H** [Th3Tr0LLeR/SkinsRestorer---Maro#238]
### What doesn't work (or what feature do you request)?

SkinsRestorer seems to be relying on getmeproxy.com, which is down since a few days. This creates massive stacktraces in bungeecord log. At some times we're getting a few thousand lines in our log each second.

```
15:23:06 [INFO] [SkinsRestorer] We couldn't update the proxy list. This usually indicates a firewall problem. A detailed error is below.
15:23:06 [SEVERE] java.net.UnknownHostException: getmeproxy.com
15:23:06 [SEVERE] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
15:23:06 [SEVERE] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
15:23:06 [SEVERE] 	at java.net.Socket.connect(Socket.java:589)
15:23:06 [SEVERE] 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
15:23:06 [SEVERE] 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
15:23:06 [SEVERE] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
15:23:06 [SEVERE] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
15:23:06 [SEVERE] 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
15:23:06 [SEVERE] 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
15:23:06 [SEVERE] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
15:23:06 [SEVERE] 	at java.security.AccessController.doPrivileged(Native Method)
15:23:06 [SEVERE] 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
15:23:06 [SEVERE] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
15:23:06 [SEVERE] 	at java.security.AccessController.doPrivileged(Native Method)
15:23:06 [SEVERE] 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
15:23:06 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
15:23:06 [SEVERE] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:48)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.getList(ProxyManager.java:20)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.MojangAPI.readURLProxy(MojangAPI.java:167)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.MojangAPI.getUUIDProxy(MojangAPI.java:118)
15:23:06 [SEVERE] 	at skinsrestorer.shared.utils.MojangAPI.getUUID(MojangAPI.java:111)
```

### How to reproduce the bug? (if a bug)
Start a bungeecord server with skinsrestorer and join with a non-premium player.

### What version of SkinsRestorer do you use?
13.3

**Comment by McLive** [comment]
Hi @theJ3H 
You can get the latest DEV-version (13.5.1) from https://skinsrestorer.net/ which fixes that issue.

**Comment by theJ3H** [comment]
Yup, that fixed my issue. Thanks.
