### ISSUE TITLE
Bungeecord MySQL Storage Problem

### ISSUE THREAD

**Issue by Zoiter7** [Th3Tr0LLeR/SkinsRestorer---Maro#26]
`15:04:32 [AVERTISSEMENT] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
    at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
    at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
    at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
    at java.lang.Thread.init(Thread.java:391)
    at java.lang.Thread.init(Thread.java:349)
    at java.lang.Thread.<init>(Thread.java:675)
    at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:613)
    at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    at skinsrestorer.shared.utils.MySQL.query(MySQL.java:115)
    at skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:130)
    at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinData(SkinStorage.java:111)
    at skinsrestorer.bungee.listeners.LoginListener.onPreLogin(LoginListener.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:491)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by Blackfire62** [comment]
Update your bungeecord to latest version.

**Comment by Zoiter7** [comment]
I can't update to latest version, but I already use 1.7.
But thanks por your support.

**Comment by Th3Tr0LLeR** [comment]
Then you should use old version of SkinsRestorer. Downloads are available :)

**Comment by Zoiter7** [comment]
I use the latest version.
