### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TheGaming2** [Th3Tr0LLeR/SkinsRestorer---Maro#28]
Why

Please help me! 
[16:00:07 ERROR]: [iTag] Unhandled exception occured in onPacketSending(PacketEvent) for iTag
java.lang.IllegalStateException: Can only process events on main thread.
at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[spigot.jar:git-Spigot-6f291ea-6026dad]
at net.md_5.itag.iTag.getSentName(iTag.java:110) ~[iTag-1.1.0-SNAPSHOT.jar:?]
at net.md_5.itag.iTag.access$000(iTag.java:28) ~[iTag-1.1.0-SNAPSHOT.jar:?]
at net.md_5.itag.iTag$1.onPacketSending(iTag.java:74) ~[iTag-1.1.0-SNAPSHOT.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:318) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:401) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:82) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.handleScheduled(NettyChannelInjector.java:367) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.onMessageScheduled(NettyChannelInjector.java:335) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib.jar:3.7.0-SNAPSHOT-b258]
at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:193) [spigot.jar:git-Spigot-6f291ea-6026dad]
at net.minecraft.server.v1_9_R1.NetworkManager.sendPacket(NetworkManager.java:142) [spigot.jar:git-Spigot-6f291ea-6026dad]
at net.minecraft.server.v1_9_R1.PlayerConnection.sendPacket(PlayerConnection.java:1088) [spigot.jar:git-Spigot-6f291ea-6026dad]
at skinsrestorer.bukkit.SkinFactoryv1_9_R1.updateSkin(SkinFactoryv1_9_R1.java:120) [SkinsRestorer.jar:?]
at skinsrestorer.bukkit.SkinFactoryv1_9_R1$1.applySkin(SkinFactoryv1_9_R1.java:63) [SkinsRestorer.jar:?]
at skinsrestorer.shared.format.SkinProfile.applySkin(SkinProfile.java:106) [SkinsRestorer.jar:?]
at skinsrestorer.bukkit.SkinFactoryv1_9_R1.applySkin(SkinFactoryv1_9_R1.java:50) [SkinsRestorer.jar:?]
at skinsrestorer.shared.api.SkinsRestorerAPI.applySkin(SkinsRestorerAPI.java:80) [SkinsRestorer.jar:?]
at skinsrestorer.bukkit.commands.Commands$1.run(Commands.java:137) [SkinsRestorer.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_73]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_73]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_73]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_73]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
[16:00:07 ERROR]: Parameters:
net.minecraft.server.v1_9_R1.PacketPlayOutPlayerInfo@4c83397e[
a=ADD_PLAYER
b=[PlayerInfoData{latency=0, gameMode=SURVIVAL, profile=com.mojang.authlib.GameProfile@48ab5ff3[id=d74faa9e-346b-3005-bb2c-0299583c5cfa,name=TheGaming,properties={textures=[com.mojang.authlib.properties.Property@5a7c2372]},legacy=false], displayName={"extra":[{"color":"gold","text":"Mezua"}],"text":""}}]
]

**Comment by Blackfire62** [comment]
This is not our problem, its problem of iTag and or ProtocolLib .
