### ISSUE TITLE
Spigot 

### ISSUE THREAD

**Issue by EtorS** [Th3Tr0LLeR/SkinsRestorer---Maro#30]
I tested this plugin ,it works, but when starting the reports these errors to the console server

`[15:16:41] [Thread-28/WARN]: Exception in thread "Thread-28" 
[15:16:41] [Thread-28/WARN]: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
[15:16:41] [Thread-28/WARN]: 	at skinsrestorer.shared.utils.SkinFetchUtils.c(SkinFetchUtils.java:97)
[15:16:41] [Thread-28/WARN]: 	at skinsrestorer.shared.utils.SkinFetchUtils$SkinFetchFailedException$Reason.<clinit>(SkinFetchUtils.java:74)
[15:16:41] [Thread-28/WARN]: 	at skinsrestorer.shared.utils.MojangAPI.getProfile(MojangAPI.java:87)
[15:16:41] [Thread-28/WARN]: 	at skinsrestorer.shared.utils.SkinFetchUtils.fetchSkinProfile(SkinFetchUtils.java:41)
[15:16:41] [Thread-28/WARN]: 	at skinsrestorer.shared.format.SkinProfile.attemptUpdate(SkinProfile.java:66)
[15:16:41] [Thread-28/WARN]: 	at skinsrestorer.bukkit.listeners.LoginListener$2.run(LoginListener.java:82)
[15:16:41] [Thread-28/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:16:41] [Thread-28/WARN]: Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
[15:16:41] [Thread-28/WARN]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[15:16:41] [Thread-28/WARN]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[15:16:41] [Thread-28/WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[15:16:41] [Thread-28/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[15:16:41] [Thread-28/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77)
[15:16:41] [Thread-28/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[15:16:41] [Thread-28/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[15:16:41] [Thread-28/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[15:16:41] [Thread-28/WARN]: 	... 7 more`

And these when someone logs into the server

`[15:18:21] [Thread-30/WARN]: Exception in thread "Thread-30" 
[15:18:21] [Thread-30/WARN]: java.lang.NoClassDefFoundError: Could not initialize class skinsrestorer.shared.utils.SkinFetchUtils$SkinFetchFailedException$Reason
[15:18:21] [Thread-30/WARN]: 	at skinsrestorer.shared.utils.MojangAPI.getProfile(MojangAPI.java:87)
[15:18:21] [Thread-30/WARN]: 	at skinsrestorer.shared.utils.SkinFetchUtils.fetchSkinProfile(SkinFetchUtils.java:41)
[15:18:21] [Thread-30/WARN]: 	at skinsrestorer.shared.format.SkinProfile.attemptUpdate(SkinProfile.java:66)
[15:18:21] [Thread-30/WARN]: 	at skinsrestorer.bukkit.listeners.LoginListener$2.run(LoginListener.java:82)
[15:18:21] [Thread-30/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by Th3Tr0LLeR** [comment]
Please give me sone info such as server version and stuff.
