### ISSUE TITLE
Paper 1.9.2 error

### ISSUE THREAD

**Issue by rErEaT** [Th3Tr0LLeR/SkinsRestorer---Maro#32]
[11:08:19] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to SkinsRestorer v11.4
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.2.jar:git-Paper-643]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.2.jar:git-Paper-643]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-643]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-643]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:348) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:174) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:912) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-643]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-643]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552) ~[?:1.8.0_71]
	at java.lang.Long.valueOf(Long.java:803) ~[?:1.8.0_71]
	at skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:162) ~[?:?]
	at skinsrestorer.bukkit.listeners.LoginListener.onLoginEvent(LoginListener.java:55) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.2.jar:git-Paper-643]
	... 15 more

**Comment by Th3Tr0LLeR** [comment]
Is this happening only if you're running timings ?

**Comment by rErEaT** [comment]
timings is always turn on when I start the server

**Comment by Th3Tr0LLeR** [comment]
The strangest thing. This is happening when i try to run async task while timings are running.

**Comment by Th3Tr0LLeR** [comment]
Fixed
