### ISSUE TITLE
SkinsRestorer-v11.4

### ISSUE THREAD

**Issue by NelsonHD** [Th3Tr0LLeR/SkinsRestorer---Maro#33]
`Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7582ff54, id=8, owner=skinsrestorer.bungee.SkinsRestorer@12359a82, task=skinsrestorer.bungee.commands.PlayerCommands$1@5270316d, delay=0, period=0, running=true) encountered an exception
java.lang.NumberFormatException: null
    at java.lang.Long.parseLong(Unknown Source)
    at java.lang.Long.valueOf(Unknown Source)
    at skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:162)
    at skinsrestorer.bungee.commands.PlayerCommands$1.run(PlayerCommands.java:111)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
`
newest bungeecord, java, SkinsRestorer and offline server.

**Comment by NelsonHD** [comment]
and /skin set ID
it will show "§4Skin fetch failed: §cAn error occured while trying to connect to mcapi.ca for skin."

**Comment by Blackfire62** [comment]
Already made a push for fixing this. Thanks for reporting.

**Comment by Th3Tr0LLeR** [comment]
Fixed.
