### ISSUE TITLE
Error with an update.

### ISSUE THREAD

**Issue by ARTIKLARTIKL** [Th3Tr0LLeR/SkinsRestorer---Maro#36]
Hey. I updated your plugin to a latest version. It gave me this error.
Error occurred while enabling SkinsRestorer v11.4 (Is it up to date?)
java.lang.NullPointerException
	at skinsrestorer.shared.utils.DataFiles.getBoolean(DataFiles.java:233) ~[?:?]
	at skinsrestorer.shared.storage.ConfigStorage.init(ConfigStorage.java:45) ~[?:?]
	at skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[my.jar:git-Spigot-6d16e64-58d972f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [my.jar:git-Spigot-6d16e64-58d972f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [my.jar:git-Spigot-6d16e64-58d972f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [my.jar:git-Spigot-6d16e64-58d972f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [my.jar:git-Spigot-6d16e64-58d972f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [my.jar:git-Spigot-6d16e64-58d972f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [my.jar:git-Spigot-6d16e64-58d972f]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

Any help?

**Comment by Th3Tr0LLeR** [comment]
Fixed.
