### ISSUE TITLE
locale is broken with latest update

### ISSUE THREAD

**Issue by xion87** [Th3Tr0LLeR/SkinsRestorer---Maro#38]
latest locale format seem to broken all messages in game, (but is working)
I think you need to add "" to these since the proposed one it contain duplication errors on yaml parser site.
There is the fixed one http://pastebin.com/ad1xFW0X

**Comment by Th3Tr0LLeR** [comment]
Its reworked yaml.

На понеделник, 11 април 2016 г. xion87 <notifications@github.com> написа:

**Comment by xion87** [comment]
what you mean?

**Comment by Th3Tr0LLeR** [comment]
It's not original Yaml. It works without quotes.

2016-04-12 1:15 GMT+03:00 xion87 <notifications@github.com>:

**Comment by xion87** [comment]
if i use your original yaml, it trow me errors everytime i use any commands

**Comment by xion87** [comment]
is the same thing ç_ç

**Comment by xion87** [comment]
`00:34:29 [AVVERTENZA] Error in dispatching command
java.lang.NullPointerException
	at java.lang.String.startsWith(String.java:1405)
	at java.lang.String.startsWith(String.java:1434)
	at skinsrestorer.shared.utils.DataFiles.set(DataFiles.java:91)
	at skinsrestorer.shared.storage.SkinStorage.removeSkinData(SkinStorage.java:66)
	at skinsrestorer.bungee.commands.PlayerCommands.execute(PlayerCommands.java:66)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:113)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by xion87** [comment]
that error is caused by /skin clear 
and other ommand /skin help /skinsrestorer help are not showing any commands (only titles)

**Comment by tuanjr** [comment]
When i translate to my language, /skin help wont show. i'm sure that i dont make mistake in yaml syntax.

**Comment by Th3Tr0LLeR** [comment]
@tuanjr Can i see ur locale ?

**Comment by tuanjr** [comment]
> PLAYER_SKIN_CHANGE_SKIN_DATA_CLEARED: &9Skin của bạn đã được xóa bỏ
PLAYER_SKIN_COOLDOWN: &cBạn chỉ được thay đổi skin mỗi %s giây
PLAYER_SKIN_CHANGE_SUCCESS: &9Skin của bạn đã được thay đổi.
PLAYER_SKIN_CHANGE_SUCCESS_DATABASE: &9Skin của bạn đã được cập nhật.
DO_YOU_WANT_SKIN: &9Nhấn vào đây nếu bạn muốn thay đổi skin.
PLAYER_HAS_NO_PERMISSION: &cYou don't have permission to do this!
DISABLED_SKIN: &cBạn không được dùng skin này
UNKNOWN_COMMAND: Unknown command. Type "/help" for help.
SKIN_FETCH_FAILED_NO_PREMIUM_PLAYER: &cKhông có skin nào tên như thế này
SKIN_FETCH_FAILED_NO_SKIN_DATA: &cNo skin data found for player with that name
SKIN_FETCH_FAILED_PARSE_FAILED: &cKhông thể giải mã skin
SKIN_FETCH_FAILED_RATE_LIMITED: &cGiới hạn
SKIN_FETCH_FAILED_MCAPI_PROBLEM: &cAn error occured while trying to connect to mcapi.ca for skin.
SKIN_FETCH_FAILED_ERROR: &cAn error has occured
SKIN_DATA_DROPPED: &9Skin data for player %player dropped
SKIN_DATA_SAVED: &9Skin data saved successfully.
SKIN_DATA_UPDATED: &9Skin data updated
SKIN_FETCH_FAILED: &4Skin fetch failed: 
MCAPI_FAILED_ERROR: &cTried to use mcapi.ca, but it failed.
TRYING_TO_USE_NCAPI: [SkinsRestorer] Getting skin from Mojang failed. Using mcapi.ca!
USE_SKIN_HELP: &9Gõ '/skin help' để xem hướng dẫn.
PLAYER_HELP: &8]&7&m-------------&r&8[ &9Hướng dẫn dùng Skin&8]&7&m-------------*r&8[
&9/skin set <skinname> &9-&a Sét skin.
&9/skin clear &9-&a Xóa skin.
ADMIN_USE_SKIN_HELP: &9Use '/skinsrestorer help' for help.
ADMIN_SET_SKIN: You set %player''s skin.
ADMIN_HELP: &8]&7&m-------------&r&8[ &9SkinsRestorer Admin Help &8]&7&m-------------*r&8[
&9/skinsrestorer drop <player> &9-&a Drops player skin data.
&9/skinsrestorer update <player> &9-&a Updates player skin data.
&9/skinsrestorer set <player> <skin name> &9-&a Sets Player's skin.
&9/skinsrestorer info &9- &aShows some info.

**Comment by tuanjr** [comment]
`PLAYER_SKIN_CHANGE_SKIN_DATA_CLEARED: &9Skin của bạn đã được xóa bỏ
PLAYER_SKIN_COOLDOWN: &cBạn chỉ được thay đổi skin mỗi %s giây
PLAYER_SKIN_CHANGE_SUCCESS: &9Skin của bạn đã được thay đổi.
PLAYER_SKIN_CHANGE_SUCCESS_DATABASE: &9Skin của bạn đã được cập nhật.
DO_YOU_WANT_SKIN: &9Nhấn vào đây nếu bạn muốn thay đổi skin.
PLAYER_HAS_NO_PERMISSION: &cYou don't have permission to do this!
DISABLED_SKIN: &cBạn không được dùng skin này
UNKNOWN_COMMAND: Unknown command. Type "/help" for help.
SKIN_FETCH_FAILED_NO_PREMIUM_PLAYER: &cKhông có skin nào tên như thế này
SKIN_FETCH_FAILED_NO_SKIN_DATA: &cNo skin data found for player with that name
SKIN_FETCH_FAILED_PARSE_FAILED: &cKhông thể giải mã skin
SKIN_FETCH_FAILED_RATE_LIMITED: &cGiới hạn
SKIN_FETCH_FAILED_MCAPI_PROBLEM: &cAn error occured while trying to connect to mcapi.ca for skin.
SKIN_FETCH_FAILED_ERROR: &cAn error has occured
SKIN_DATA_DROPPED: &9Skin data for player %player dropped
SKIN_DATA_SAVED: &9Skin data saved successfully.
SKIN_DATA_UPDATED: &9Skin data updated
SKIN_FETCH_FAILED: &4Skin fetch failed: 
MCAPI_FAILED_ERROR: &cTried to use mcapi.ca, but it failed.
TRYING_TO_USE_NCAPI: [SkinsRestorer] Getting skin from Mojang failed. Using mcapi.ca!
USE_SKIN_HELP: &9Gõ '/skin help' để xem hướng dẫn.
PLAYER_HELP: &8]&7&m-------------&r&8[ &9Hướng dẫn dùng Skin&8]&7&m-------------*r&8[
&9/skin set <skinname> &9-&a Sét skin.
&9/skin clear &9-&a Xóa skin.
ADMIN_USE_SKIN_HELP: &9Use '/skinsrestorer help' for help.
ADMIN_SET_SKIN: You set %player''s skin.
ADMIN_HELP: &8]&7&m-------------&r&8[ &9SkinsRestorer Admin Help &8]&7&m-------------*r&8[
&9/skinsrestorer drop <player> &9-&a Drops player skin data.
&9/skinsrestorer update <player> &9-&a Updates player skin data.
&9/skinsrestorer set <player> <skin name> &9-&a Sets Player's skin.
&9/skinsrestorer info &9- &aShows some info.`

**Comment by tuanjr** [comment]
http://paste.ubuntu.com/15819249/

**Comment by Th3Tr0LLeR** [comment]
What if you make it in one line and use \n for newline ?

**Comment by tuanjr** [comment]
i will test it.

**Comment by Th3Tr0LLeR** [comment]
Should be fixed, but i didn't update the code online.

**Comment by Th3Tr0LLeR** [comment]
fixed
