### ISSUE TITLE
SkinsRestorer-v11.5.2

### ISSUE THREAD

**Issue by Airnexus** [Th3Tr0LLeR/SkinsRestorer---Maro#54]
`Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7582ff54, id=5, owner=skinsrestorer.bungee.SkinsRestorer@12359a82, task=skinsrestorer.bungee.commands.PlayerCommands$1@5e101613, delay=0, period=0, running=true) encountered an exception
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Unknown Source)
	at java.lang.Long.valueOf(Unknown Source)
	at skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:162)
	at skinsrestorer.bungee.commands.PlayerCommands$1.run(PlayerCommands.java:111)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`
with command "/skin set playerid"
Plz solve it, i got this problem for more than 100 times.. :(

**Comment by Blackfire62** [comment]
You arent using latest version, this error is already fixed...

**Comment by Airnexus** [comment]
Yes, lastest version of SkinRestorer , BungeeCord , Spigot and java. But still error...
