### ISSUE TITLE
/skinsrestorer drop with v11.5.2

### ISSUE THREAD

**Issue by Augustin37** [Th3Tr0LLeR/SkinsRestorer---Maro#57]
Hello, first I want to say thank you because you're doing a great job for this plugin! :D 

I don't know if I'm the only one to have this error, but when I type **/skins restorer drop playername**, I have this error:
``` java
[17:32:51] [Server thread/INFO]: Augustin37 issued server command: /skinsrestorer drop Azrod
[17:32:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'skinsrestorer' in plugin SkinsRestorer v11.5.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.2.jar:git-Paper-716]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-716]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1388) [patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-716]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:813) [patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-716]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-716]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at skinsrestorer.shared.utils.DataFiles.removePath(DataFiles.java:415) ~[?:?]
	at skinsrestorer.shared.storage.SkinStorage.removeSkinData(SkinStorage.java:64) ~[?:?]
	at skinsrestorer.bukkit.commands.Commands.dropData(Commands.java:162) ~[?:?]
	at skinsrestorer.bukkit.commands.Commands.onCommand(Commands.java:80) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.2.jar:git-Paper-716]
	... 15 more
```
I don't know if this could help (maybe not) but it worked well in version v11.0-v2 and maybe after but I think it's broken since v11.3

Hope that you will find the problem :) Thank you again for your work :)

PS: I'm using PaperSpigot (latest) and Java 8

**Comment by Th3Tr0LLeR** [comment]
Never knew about that problem :D I will fix it.

**Comment by Augustin37** [comment]
fast repair :D thank you !!

**Comment by Th3Tr0LLeR** [comment]
It would be fast if I had enough time :D

**Comment by Augustin37** [comment]
It is fast enough :P
