### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by x4sTaTic** [Th3Tr0LLeR/SkinsRestorer---Maro#76]
[WARNING] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
 at

[SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@543295b0, id=1, owner=skinsrestorer.bungee.SkinsRestorer@1530c739, task=skinsrestorer.bungee.metrics.Metrics$1@7a35b0f5, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
 at skinsrestorer.bungee.metrics.Metrics.appendJSONPair(Metrics.java:579)
 at skinsrestorer.bungee.metrics.Metrics.postPlugin(Metrics.java:382)
 at skinsrestorer.bungee.metrics.Metrics.access$4(Metrics.java:359)
 at skinsrestorer.bungee.metrics.Metrics$1.run(Metrics.java:249)
 at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
07:39:42 [WARNING] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
 at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
 at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
 at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
 at java.lang.Thread.init(Thread.java:391)
 at java.lang.Thread.init(Thread.java:349)
 at java.lang.Thread.<init>(Thread.java:548)
 at de.De24.BungeeTools.Metrics.start(Metrics.java:252)
 at de.De24.BungeeTools.BgTools.onEnable(BgTools.java:76)
 at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:220)
 at net.md_5.bungee.BungeeCord.start(BungeeCord.java:242)
 at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:50)
 at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Blackfire62** [comment]
BungeeTools error, not SkinsRestorer error . (Meterics are not important)
