### ISSUE TITLE
1.10

### ISSUE THREAD

**Issue by Infextro** [Th3Tr0LLeR/SkinsRestorer---Maro#88]
Good day.
When start plugin on Spigot 1.10:

[11:06:35] [Server thread/INFO]: [SkinsRestorer] Loading SkinsRestorer v11.6.1
[11:06:35] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v11.6.1
[11:06:35] [Server thread/INFO]: .[0;31;1m[SkinsRestorer] The version v1_10_R1 is not supported by SkinsModule..[m
[11:06:35] [Server thread/INFO]: [SkinsRestorer] Disabling SkinsRestorer v11.6.1
[11:06:35] [Server thread/INFO]: .[0;32;22m==============================================.[m
[11:06:35] [Server thread/INFO]: .[0;33;1m  SkinsRestorer Updater.[m
[11:06:35] [Server thread/INFO]: .[0;33;1m .[m
[11:06:35] [Server thread/INFO]: .[0;36;1m    You are running v.[0;32;1m11.6.1.[m
[11:06:35] [Server thread/INFO]: .[0;32;1m    The latest version of SkinsRestorer!.[m
[11:06:35] [Server thread/INFO]: .[0;33;1m .[m
[11:06:35] [Server thread/INFO]: .[0;32;22m==============================================.[m
[11:06:35] [Server thread/ERROR]: Error occurred while enabling SkinsRestorer v11.6.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:141) ~[spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at skinsrestorer.bukkit.metrics.Metrics.start(Metrics.java:211) ~[?:?]
        at skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:212) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-da278d1-b2f31b7]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

Thanks!

**Comment by Blackfire62** [comment]
Well since the version currently on spigot site is outdated, you can try out my current alpha version  uploaded here https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/master/SkinsRestorer-11.7-Alpha.jar . 

I upade it every once a time t

**Comment by infernvs** [comment]
That alpha version works on 1.10 version

**Comment by infernvs** [comment]
[15:23:26] [Server thread/ERROR]: Could not load 'plugins/SkinsRestorer-11.7-Alpha.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_91]
        at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_91]
        at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_91]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_91]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        ... 5 more
[15:23:26] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[15:23:27] [Server thread/ERROR]: Could not load 'plugins/denizen-0.9.8-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/LoggerOutputStream
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/LoggerOutputStream
        at net.aufdemrand.denizen.Denizen.<clinit>(Denizen.java:270) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_9_R1.LoggerOutputStream
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
        at net.aufdemrand.denizen.Denizen.<clinit>(Denizen.java:270) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        ... 6 more
