### ISSUE TITLE
plugin don't change skin and do nothing

### ISSUE THREAD

**Issue by PimaPvP** [Th3Tr0LLeR/SkinsRestorer---Maro#95]
console:
[12:51:27] [Thread-14/WARN]: Exception in thread "Thread-14"
[12:51:27] [Thread-14/WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.removePlayer(Lnet/minecraft/server/v1_7_R4/EntityPlayer;)Lnet/minecraft/server/v1_7_R4/PacketPlayOutPlayerInfo;
[12:51:27] [Thread-14/WARN]: at skinsrestorer.bukkit.SkinFactoryv1_7_R4.updateSkin(SkinFactoryv1_7_R4.java:76)
[12:51:27] [Thread-14/WARN]: at skinsrestorer.bukkit.SkinFactoryv1_7_R4$1.applySkin(SkinFactoryv1_7_R4.java:56)
[12:51:27] [Thread-14/WARN]: at skinsrestorer.shared.format.SkinProfile.applySkin(SkinProfile.java:106)
[12:51:27] [Thread-14/WARN]: at skinsrestorer.bukkit.SkinFactoryv1_7_R4.applySkin(SkinFactoryv1_7_R4.java:44)
[12:51:27] [Thread-14/WARN]: at skinsrestorer.shared.api.SkinsRestorerAPI.applySkinBukkit(SkinsRestorerAPI.java:82)
[12:51:27] [Thread-14/WARN]: at skinsrestorer.bukkit.listeners.LoginListener$2.run(LoginListener.java:88)
[12:51:27] [Thread-14/WARN]: at java.lang.Thread.run(Unknown Source)

When I do for exemple /skin set pseudo, do nothing.

I use spigot 1.7.10 and last version of skinrestorer.
Tanks.
ps: i'm french.

**Comment by Blackfire62** [comment]
Hm, I did not make support for 1.7 version.
Didnt know anyone uses that version anymore.

**Comment by Blackfire62** [comment]
Do you even want me to reverse the 1.7 packets and add support for them, or will we just declare 1.7 version as busted and continue with the latest versions or 1.8+ ?

**Comment by PimaPvP** [comment]
I don't understand, what i need to do ? :/ I want 1.7 server and i can't up to 1.8 because i hate this version :/

**Comment by Blackfire62** [comment]
Well, 1.7 is just the version before packet rework (or whatever else has been reworked) . You might remember having no mods or whatever for quite some time because of this rework.

What it means, is, im not much into making support for 1.7 version as I would have to add support for all the old packets and other stuff.

If there was a quite bigger demand for 1.7 version support, i might be down for it, but nontheless, there is no point in using that version anymore.

**Comment by PimaPvP** [comment]
So you can't resolve the problem ?

**Comment by Blackfire62** [comment]
Not that i cant, but i dont want to. If more people will request 1.7 support, ill do it, but otherwise its just a waste of time

**Comment by Bodyash** [comment]
Any fixes for 1.10? Skinsrestorer kick my players, skins working badl. etc

**Comment by GeomcGR** [comment]
Please help me! it dont worked in 1.9.4 it says my skin chance but it didnt . i was trying it with diffrent skins.
